<script setup>
const cpus = [
  {
    Name: 'i5 12450H',
    Architecture: 'Alder Lake H',
    Cores: 8,
    Threads: 12,
    Overclock: 'No',
    L2Cache: '7 MB',
    L3Cache: '12 MB',
    Technology: '10 nm',
    Geekbench6Single: 2218,
  },
  {
    Name: 'r5 5600X',
    Architecture: 'Vermeer(Zen 3)',
    Cores: 6,
    Threads: 12,
    Overclock: 'Yes',
    L2Cache: '3 MB',
    L3Cache: '32 MB',
    Technology: '7 nm',
    Geekbench6Single: 2113,
  },
  {
    Name: 'snapdragon 765',
    Architecture: 'Kryo 475',
    Cores: 8,
    Threads: 8,
    Overclock: 'No',
    L2Cache: '0 MB',
    L3Cache: '2 MB',
    Technology: '7 nm',
    Geekbench6Single: 782,
  },
  {
    Name: 'r5 1400',
    Architecture: 'Summit Ridge(Zen)',
    Cores: 4,
    Threads: 8,
    Overclock: 'Yes',
    L2Cache: '0 MB',
    L3Cache: '8 MB',
    Technology: '14 nm',
    Geekbench6Single: 947,
  },
  {
    Name: 'phenom II 955',
    Architecture: 'Deneb(K10)',
    Cores: 4,
    Threads: 4,
    Overclock: 'Yes',
    L2Cache: '0 MB',
    L3Cache: '6 MB',
    Technology: '45 nm',
    Geekbench6Single: 351,
  },
  {
    Name: 'i7 12700',
    Architecture: 'Alder Lake S',
    Cores: 12,
    Threads: 20,
    Overclock: 'No',
    L2Cache: '12 MB',
    L3Cache: '25 MB',
    Technology: '10 nm',
    Geekbench6Single: 2500,
  },
];
</script>
